#!/usr/bin/env bash

# hyprctl
hyprctl setcursor Catppuccin-Macchiato-Dark-Cursors 24 &
~/.config/hypr/scripts/monitors.sh &

# clipboard
wl-paste --type text --watch cliphist store & #Stores only text data

# wallpaper
hyprpaper &

hypridle &

# other
/nix/store/$(ls -la /nix/store | grep polkit-gnome | grep '^d' | awk '{print $9}' | head -n 1)/libexec/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
